### ISSUE TITLE
Same issue with 'the_tweet_search.py' code

### ISSUE THREAD

**Issue by digitalpaula** [ptwobrussell/Mining-the-Social-Web#11]
Hi Matthew,

I thought I could move on in the book but came across the same problem when running the tweet search code.  

I entered teaparty as the argument in the PythonWin argument line and got the same error.  

error: [Errno 10061] No connection could be made because the target machine actively refused it

This is the error code that proceeded the above:

  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 325, in RunScript
    exec codeObject in **main**.**dict**
  File "C:\Python27\search.py", line 23, in <module>
    db = server.create(DB)
  File "build\bdist.win32\egg\couchdb\client.py", line 193, in create
    self.resource.put_json(validate_dbname(name))
  File "build\bdist.win32\egg\couchdb\http.py", line 405, in put_json
    status, headers, data = self.put(_a, *_k)
  File "build\bdist.win32\egg\couchdb\http.py", line 384, in put
    return self._request('PUT', path, body=body, headers=headers, **params)
  File "build\bdist.win32\egg\couchdb\http.py", line 419, in _request
    credentials=self.credentials)
  File "build\bdist.win32\egg\couchdb\http.py", line 239, in request
    resp = _try_request_with_retries(iter(self.retry_delays))
  File "build\bdist.win32\egg\couchdb\http.py", line 205, in _try_request_with_retries
    raise e

Would really love to run the tweet search code on other topics.  Please advise.  

Thanks.

Regards,
Paula

**Comment by ptwobrussell** [comment]
Ok, so like I commented on #10, I bet the issue is related to your firewall settings somehow. It doesn't make a lot of sense that anything else could be preventing you from initiating a connection to CouchDB. The good news is that if some of the suggestions I mentioned don't help, you should be able to totally isolate the issue in an interpreter session (eliminating the rest of the script entirely) and ping some people on #couchb on freenode (IRC) and get some realtime help immediately. I'm sure that this is a simple configuration issue related to Windows, but I just don't' know how to help you with it since I don't use Windows and don't have access to a Windows VM that I could try to use for debugging.

**Comment by digitalpaula** [comment]
Ok, I will contact these folks once I figure out why my localhost isn't rendering correctly.   Thanks again Matthew.

**Comment by digitalpaula** [comment]
Hi Matthew, just wanted to provide you an update that everything's working fine now.  It was an IIS (web server) issue.  Thanks so much for leading me down the right path in identifying the cause with the localhost test.  I'm now executing the code and it's populating the database....working through the rest of the examples in the book now.  Paula
