### ISSUE TITLE
Trend_timeline not working

### ISSUE THREAD

**Issue by Ramaznaz** [ptwobrussell/Mining-the-Social-Web#19]
I'm trying to run the code written here: 
https://github.com/ptwobrussell/Recipes-for-Mining-Twitter/blob/master/recipe__get_search_results_for_trending_topic.py

And get this:

Traceback (most recent call last):
  File "C:\Python27\trend_timeline.py", line 19, in <module>
    trends = json.dumps(t.trends(), indent=1)
  File "C:\Documents and Settings\Zanzamar\Datos de programa\Python\Python27\site-packages\twitter\api.py", line 165, in **call**
    return self._handle_response(req, uri, arg_data)
  File "C:\Documents and Settings\Zanzamar\Datos de programa\Python\Python27\site-packages\twitter\api.py", line 180, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
TwitterHTTPError: Twitter sent status 404 for URL: 1/trends.json using parameters: ()
details: <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Language" content="en-us">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter / ?</title>
    <link href="//si0.twimg.com/sticky/error_pages/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="/errors/fullscreen_errors.css">
  </head>
  <body>
    <div class="topbar js-topbar">
      <div class="global-nav" data-section-term="top_nav">
        <div class="global-nav-inner">
          <div class="container">
            <ul class="nav js-global-actions">
              <li class="home">
                <a href="//twitter.com">
                  <span><i class="nav-home-logged-out"></i></span>
                </a>
              </li>
            </ul>
            <div class="pull-right">
              <ul class="nav secondary-nav">
                <li><a href="//twitter.com" id="homeLink">Home &rarr;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="blue-sky">
      <div class="body-content">
        <h1>Sorry, that page doesn’t exist!</h1>
        <p>Thanks for noticing&mdash;we're going to fix it up and have things back to normal soon.</p>
        <form class="search-404" action="//twitter.com/search/users" method="get">
          <label for="search_users_q" id="search_label">Search for a username, first or last name</label>
          <input type="hidden" name="category" value="people">
          <input type="hidden" name="source" value="find_on_twitter">
          <input id="search_users_q" name="q" type="text" placeholder="Search for a username, first or last name">
          <input class="btn" id="search_users_submit" type="submit" value="Search">
        </form>
        <div class="footer">
          <ul class="languages">
            <li><a onclick="displayLanguage('id');return false;" href="#">Bahasa Indonesia</a></li>
            <li><a onclick="displayLanguage('msa');return false;" href="#">Bahasa Melayu</a></li>
            <li><a onclick="displayLanguage('de');return false;" href="#">Deutsch</a></li>
            <li class="first"><a onclick="displayLanguage('en');return false;" href="#">English</a></li>
            <li><a onclick="displayLanguage('es');return false;" href="#">Español</a></li>
            <li><a onclick="displayLanguage('fil');return false;" href="#">Filipino</a></li>

.... output truncated as it is a very long code...

I'm using ActivePython with Python 2.7 (PC), installed twitter and json packs.

**Comment by ptwobrussell** [comment]
Are you running the actual code that is currently checked into GitHub or did you type it in out of the text that's printed in the paper book? I ask because the line of code that is causing the stack trace in your note above ( trends = json.dumps(t.trends(), indent=1) ) is nowhere in the file that you are citing (

<pre>https://github.com/ptwobrussell/Recipes-for-Mining-Twitter/blob/master/recipe__get_search_results_for_trending_topic.py</pre>

), although it used to be there in an earlier revision (see <pre>https://github.com/ptwobrussell/Recipes-for-Mining-Twitter/commit/1be3fbb1ace322b1f88782a3d60ed1abb9e6d6ad#recipe__get_search_results_for_trending_topic.py</pre>), which was updated because of Twitter changing their API on this particular call.

I believe the solution to the problem you are mentioning in this particular case (which was also alluded to in your Amazon review) may be that you just need to re-checkout or freshen your checkout.

Give this a whirl and let me know if it helps. I'll leave the issue open for now until you verify that you can get this script to run.

**Comment by ptwobrussell** [comment]
At this point in time, the entire repo https://github.com/ptwobrussell/Recipes-for-Mining-Twitter needs updating for Twitter v1.1 compatibility, so I'm going to close this issue because I think it may have since been resolved, but is effectively moot at this point even if it's not. Please keep an eye on the Recipes-for-Mining-Twitter repository for updates if you're interested in using that code. Thanks.
