### ISSUE TITLE
Chapter1.py missing examples 1-5 and 1-6

### ISSUE THREAD

**Issue by pfaffman** [ptwobrussell/Mining-the-Social-Web#52]
And lots of other stuff that's in the book I just bought (e.g., US examples missing). I'd expect this code to be ahead of what's in the book, not behind it.

**Comment by ptwobrussell** [comment]
Just so that we can get on the same page - did you just buy the O'Reilly Early Access ebook for the 2nd Edition (a work still in progress but available for sale in an early release) or the 1st Edition that's been around for a while now? This particular code repository is for the first edition and contains collections of scripts (none of which are named Chapter1.py) and https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition contains the code for the 2nd Edition. The big difference in the 2nd Edition is that all of the code is organized into an IPython Notebook format as opposed to individual scripts, so I am assuming that perhaps you might be looking at the 1st Edition text but referencing the code from the 2nd Edition? In the 2nd Edition repo, there is a file called Chapter1.ipynb. Let me know, because I do want to help you.

**Comment by pfaffman** [comment]
Well, that explains a lot! Mea culpa. Many thanks. That's what I get for googling and not paying attention.

Please consider updating the readme for the 1st edition to tell people not to do what I did.

On a related note (that probably also does not belong here). Is there a way to submit typos? P. 6: s/crate/create/

Thanks for your quick response.

**Comment by ptwobrussell** [comment]
I will definitely update the 1st Edition readme and apologize for the confusion. Please reach back out with any questions you might have as you plug along with Mining the Social Web.

The 2nd Ed. early access edition hasn't been copyedited in any way yet, so we'll take it through an official wave of grammatical gymnastics, typesetting, etc. before it goes final later this summer. Fortunately, the publisher helps a lot with those things. What I could really use your feedback on, though, is with regard to any technical hurdles you encounter or anything that seems awry, missing, or suspect in terms of data analysis. Those are the things that I'm most worried about at this point as I wrap up the 2nd Ed. updates...
