### ISSUE TITLE
Example 2-7,Why I get a null result?

### ISSUE THREAD

**Issue by leithlee** [ptwobrussell/Mining-the-Social-Web#55]
Hello!
  I use the command about "python microformats_foodnetwork_hrecipe.py http://www.foodnetwork.com/recipes/alton-brown/pad-thai-recipe/index.html"

Result:I get a '{}',why i don't get the parse result!

thanks！

**Comment by ptwobrussell** [comment]
Unfortunately, Food Network discontinued the use of microformats some time ago, and these examples for Food Network (and also Yelp) no longer work. In fact, in the 2nd Edition of Mining the Social Web,  I am taking a slightly different approach to teaching this content, because in general, microformats seem to have fizzled out a bit. I am sorry for the inconvenience, but that's the best advice I know to offer. It's not an issue with the code; it's an issue with the underlying content, and you can confirm this for yourself by viewing the HTML source if you'd like to verify for yourself.

**Comment by leithlee** [comment]
I've viewed the original HTML page, thank you! I know the question！
