### ISSUE TITLE
Running iPython Notebook for 1st Edition

### ISSUE THREAD

**Issue by terminator1** [ptwobrussell/Mining-the-Social-Web#57]
I have successfully downloaded the repo for the 1st edition and got the iPython notebook in Linux started.

I am using the vagrant instance from 2nd edition.
As a result, upon initial startup of iPython notebook on VM, it says there is a conflict with localhost:8888 and redirected to localhost:8889

Problem is, I can't access localhost:8889 on the browser on my host machine.  
I can't seem to find the shadow directory on my host machine to modify bootstrap.sh either.

Below is an image of the initial startup.  Any insight is appreciated. Thanks!

![ipython_prob](https://f.cloud.github.com/assets/4460845/608625/0164fc6e-cd64-11e2-913f-b730a12eb089.jpg)

**Comment by ptwobrussell** [comment]
Vagrant isn't able to map to port 8888 because you have something else running on that port. You can figure out what's running on it by just going to http://localhost:8888 in your browser. If nothing is running on that port, then it's likely that somehow the virtual machine is just trying it up. Not sure off the top of my head how you would figure that out in Windows, but on Linux you could type something like "lsof -i :8888" and get the process that is running and kill it. Maybe you can do something similar through a Windows GUI. Would have to look into it more, but start with what you know and work from there.

As far as hitting port 8889 - you'll have to modify the Vagrantfile to pass through ports to your host machine. Once you open that file up and look at it, it should be pretty obvious what to do - just copy/paste/modify one line in there.

Hope that helps.

**Comment by ptwobrussell** [comment]
I think we've worked though this by now and it is safe to close. Re-open if you feel differently.
